# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shopWorking

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: shop_frontend_ebiznes
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2

      - name: Login Docker
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag spaniel24/shop_frontend:${{ github.sha }}

      - name: Docker Push
        run: docker push spaniel24/shop_frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_276dd9ed5d4946e39ea1643a42f67fcf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f2a0c127f9e4b36af5289a30d513444 }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shopWorking'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee80c2a73f614eeda0985057981887db }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_276dd9ed5d4946e39ea1643a42f67fcf }}/shop_frontend:${{ github.sha }}'
